### PR TITLE
Add readiness probe support for consul check

### PR DESCRIPTION
**Pull request by rymdo**
PR adds the optional use of readiness probe for consul checks and the ability to enable/disable liveness/readiness probes via annotations. Useful when using the readiness probe for draining/terminating a pod with a non 200 status code, in our case responding with 429 to flag the pod with "warning" in consul.

### CODE REVIEW

**Comment by webmutation** [comment]
Hi, any idea when this will be merged? It would be very useful for our use case.

**Comment by tczekajlo** [comment]
@rymdo 👋🏻  Can you resolve conflicts? The PR looks good to me.

**Comment by rymdo** [comment]
@tczekajlo Should be fixed now 😁

**Review by tczekajlo — APPROVED** [review]
LGTM

**Comment by tczekajlo** [comment]
@rymdo Thanks a lot for your PR 🙏🏻

**Comment by webmutation** [comment]
Will you guys build a new docker image, the one on docker hub is pretty old. Thanks

**Comment by tczekajlo** [comment]
A new image is available here https://hub.docker.com/r/tczekajlo/kube-consul-register/tags

**Pull request merged**
